version: "2.1"

networks:
  log-app-network:
    name: log-app-network

services:
  log-app:
    networks:
      - log-app-network
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017

  mongodb:
    image: mongo:4
    environment:
      MONGO_INITDB_DATABASE: logs
    expose:
      - 27017
    networks:
      - log-app-network
