version: "2"

volumes:
  nodemodules:
    external: true

services:
  base:
    image: node:alpine
    volumes:
      - nodemodules:/app/node_modules
      - .:/app
    working_dir: /app

  install:
    extends:
      service: base
    command: npm i
