version: "2.1"

volumes:
  mongo-db-data:
    driver: local
    driver_opts:
      type: none
      device: ${MONGODB_FILES_PATH}
      o: bind

services:
  logging-app:
    image: ${LOGGING_APP_REPO_URL}
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=production

  mongodb:
    volumes:
      - mongo-db-data:/data/db
